#!/bin/sh
set -e

exe=
case "$1" in
    pep8|pyflakes3|pylint3)
        exe="$1"
        ;;
    *)
        echo "run-helper pep8|pyflakes3|pylint3"
        exit 1
        ;;
esac

echo "= $exe ="
for i in ./clickreviews/*py \
         ./clickreviews/tests/*py \
         ./bin/click-review \
         ./bin/create-snap-declaration \
         ./bin/snap-check-* ; do
    if echo "$i" | grep -q 'cr_.*\.py' ; then
        continue
    fi
    echo "Checking $i"
    "$exe" "$i"
done

if [ -z "$CHECK_CLICK_FILES" ]; then
    echo "Use CHECK_CLICK_FILES=1 to check click support"
    exit 0
fi
for i in ./clickreviews/cr_*py \
         ./clickreviews/tests/test_cr_*py \
         ./bin/click-check-* \
         ./bin/click-show-files \
         ./bin/update-* ; do
    echo "Checking $i"
    "$exe" "$i"
done
