#!/bin/sh
set -e

# needed when run from snapcraft
export PYTHONPATH=./
SNAPDIR="$(pwd)"
export MAGIC="$SNAPDIR/../install/usr/share/misc/magic"

# eventually
#make check
make functest-updates

make coverage
make coverage-report
make syntax-check

# eventually
#make check-names
