#!/bin/sh
set -e

exe=
args=
env=
case "$1" in
    flake8)
        exe="$1"
        ;;
    black)
        exe="$1"
        # for now, only check
        args="--diff --quiet"
        ;;
    pylint3|pylint)
        exe="$1"
        env="PYTHONPATH=."
        # for now, only errors
        args="-E --disable=no-member"
        ;;
    *)
        echo "run-helper black|flake8|pylint3|pylint"
        exit 1
        ;;
esac

echo "= $exe ="
if [ -n "$env" ]; then
  export "$env"
fi
for i in ./reviewtools/*py \
         ./reviewtools/tests/*py \
         ./bin/snap-review \
         ./bin/create-snap-declaration \
         ./bin/dump-tool \
         ./bin/get-base-declaration \
         ./bin/store-query \
         ./bin/snap-updates-available \
         ./bin/snap-check-* \
         ./bin/snap-verify-* ; do
    if echo "$i" | grep -q 'snap-check-notices' ; then
        continue  # shell
    fi
    echo "Checking $i"
    "$exe" $args "$i"
done
